version: '3'

services:
  app:
    image: marcosrodriguessilva/car-service:v4
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: car
      MYSQL_PASSWORD: root
      MYSQL_USERNAME: root
      REDIS_HOST: redis
    depends_on:
      - db
      - cache

  db:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car
      MYSQL_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  cache:
    image: redis:bullseye
    ports:
      - "6373:6379"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"