version: '3'

services:
  db:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car
      MYSQL_PASSWORD: root
  cache:
    image: redis:bullseye
    ports:
      - "6373:6379"